name: Train and Deploy on Azure ML

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Azure ML CLI
      run: |
        pip install azure-cli
        az extension add -n ml -y

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Training Job
      run: |
        az ml job create \
          --file .azureml/job.yml \
          --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

    - name: Get Latest Job ID
      id: get-job-id
      run: |
        JOB_ID=$(az ml job list \
          --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --query "[0].name" -o tsv)
        echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT

    - name: Download model from Azure ML job output
      run: |
        az ml job download \
          --name ${{ steps.get-job-id.outputs.job_id }} \
          --output-name model_output \
          --download-path ./outputs \
          --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

    - name: Register Model
      run: |
        az ml model create \
          --name my-model \
          --path ./outputs/model.pkl \
          --type custom_model \
          --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

    - name: Deploy Model to Endpoint
      run: |
        az ml online-endpoint create \
          --file .azureml/deploy.yml \
          --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || \
        az ml online-endpoint update \
          --file .azureml/deploy.yml \
          --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
