name: Train and Deploy on Azure ML

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Azure ML CLI
      run: |
        pip install azure-cli
        az extension add -n ml -y

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Training Job
      run: |
        az ml job create --file .azureml/job.yml --workspace-name YOUR_WS --resource-group YOUR_RG --subscription-id YOUR_SUBSCRIPTION

    - name: Register Model
      run: |
        az ml model create --name my-model --path ./outputs/model.pkl --type custom_model --workspace-name YOUR_WS --resource-group YOUR_RG

    - name: Deploy Model to Endpoint
      run: |
        az ml online-endpoint create --file .azureml/deploy.yml --workspace-name YOUR_WS --resource-group YOUR_RG || \
        az ml online-endpoint update --file .azureml/deploy.yml --workspace-name YOUR_WS --resource-group YOUR_RG
